import { registerEnumType } from '@nestjs/graphql';

export enum TechLogo {
  C = 'C',
  Cpp = 'Cpp',
  HTML5 = 'HTML5',
  CSS3 = 'CSS3',
  JavaScript = 'JavaScript',
  Angular = 'Angular',
  React = 'React',
  ReactNative = 'ReactNative',
  Expo = 'Expo',
  Sass = 'Sass',
  Vue = 'Vue',
  Java = 'Java',
  Python = 'Python',
  Docker = 'Docker',
  Kubernetes = 'Kubernetes',
  MySQL = 'MySQL',
  MariaDB = 'MariaDB',
  Spring = 'Spring',
  SpringBoot = 'SpringBoot',
  Grails = 'Grails',
  Hibernate = 'Hibernate',
  NestJS = 'NestJS',
  TypeORM = 'TypeORM',
  Flask = 'Flask',
  Django = 'Django',
  NextJS = 'NextJS',
  ApolloClient = 'ApolloClient',
  Relay = 'Relay',
  ReactQuery = 'ReactQuery',
  SWR = 'SWR',
  RtkQuery = 'RtkQuery',
  PostgreSQL = 'PostgreSQL',
  Oracle = 'Oracle',
  Mssql = 'Mssql',
  MongoDB = 'MongoDB',
  Npm = 'NPM',
  Yarn = 'Yarn',
  Pnpm = 'PNPM',
  Vite = 'Vite',
  AntDesign = 'AntDesign',
  Storybook = 'Storybook',
  ECharts = 'ECharts',
  MaterialUI = 'MaterialUI',
  Redux = 'Redux',
  Recoil = 'Recoil',
  TypeScript = 'TypeScript',
  Nginx = 'Nginx',
  ApacheTomcat = 'ApacheTomcat',
  GithubActions = 'GithubActions',
  Firebase = 'Firebase',
  Jira = 'Jira',
  Figma = 'Figma',
}

registerEnumType(TechLogo, {
  name: 'TechLogo',
  description: '프레임워크, 라이브러리 로고',
  valuesMap: {
    C: { description: 'C Language' },
    Cpp: { description: 'C++ Language' },
    HTML5: { description: 'HTML5' },
    CSS3: { description: 'CSS3' },
    JavaScript: { description: 'JavaScript' },
    Angular: { description: 'Angular' },
    React: { description: 'React' },
    ReactNative: { description: 'React Native' },
    Expo: { description: 'Expo' },
    Sass: { description: 'Sass (SCSS)' },
    Vue: { description: 'Vue.js' },
    Java: { description: 'Java' },
    Python: { description: 'Python' },
    Docker: { description: 'Docker' },
    Kubernetes: { description: 'Kubernetes' },
    MySQL: { description: 'MySQL Database' },
    MariaDB: { description: 'MariaDB Database' },
    Spring: { description: 'Spring MVC' },
    SpringBoot: { description: 'Spring Boot' },
    Grails: { description: 'Grails' },
    Hibernate: { description: 'Hibernate' },
    NestJS: { description: 'Nest.js' },
    TypeORM: { description: 'TypeORM' },
    Flask: { description: 'Flask' },
    Django: { description: 'Django' },
    NextJS: { description: 'Next.js' },
    ApolloClient: { description: 'Apollo Client' },
    Relay: { description: 'React Relay' },
    ReactQuery: { description: 'React Query' },
    SWR: { description: 'SWR' },
    RtkQuery: { description: 'RTK Query' },
    PostgreSQL: { description: 'PostgreSQL Database' },
    Oracle: { description: 'Oracle Database' },
    Mssql: { description: 'MS-SQL Database' },
    MongoDB: { description: 'MongoDB' },
    Npm: { description: 'NPM' },
    Yarn: { description: 'Yarn' },
    Pnpm: { description: 'PNPM' },
    Vite: { description: 'Vite' },
    AntDesign: { description: 'Ant Design' },
    Storybook: { description: 'Storybook' },
    ECharts: { description: 'ECharts.js' },
    MaterialUI: { description: 'Material UI' },
    Redux: { description: 'Redux' },
    Recoil: { description: 'Recoil' },
    TypeScript: { description: 'TypeScript' },
    Nginx: { description: 'Nginx' },
    ApacheTomcat: { description: 'Apache Tomcat' },
    GithubActions: { description: 'Github Actions' },
    Firebase: { description: 'Firebase SDK' },
    Jira: { description: 'Jira' },
    Figma: { description: 'Figma' },
  },
});
